#!/usr/bin/env python3
"""Validate release-plz.toml against the schema generated by release-plz."""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
CONFIG = ROOT / "release-plz.toml"


class ValidationError(Exception):
    pass


def release_plz_binary() -> str:
    return os.environ.get("RELEASE_PLZ", "release-plz")


def load_schema() -> dict[str, Any]:
    with tempfile.TemporaryDirectory(prefix="physa-release-plz-schema.") as tmp:
        subprocess.run(
            [release_plz_binary(), "generate-schema"],
            cwd=tmp,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        return json.loads((Path(tmp) / ".schema" / "latest.json").read_text())


def resolve_ref(schema: dict[str, Any], ref: str) -> dict[str, Any]:
    if not ref.startswith("#/"):
        raise ValidationError(f"unsupported external schema reference: {ref}")

    node: Any = schema
    for part in ref.removeprefix("#/").split("/"):
        node = node[part]
    if not isinstance(node, dict):
        raise ValidationError(f"schema reference does not resolve to an object: {ref}")
    return node


def type_matches(value: Any, expected: str) -> bool:
    if expected == "null":
        return value is None
    if expected == "object":
        return isinstance(value, dict)
    if expected == "array":
        return isinstance(value, list)
    if expected == "string":
        return isinstance(value, str)
    if expected == "boolean":
        return isinstance(value, bool)
    if expected == "integer":
        return isinstance(value, int) and not isinstance(value, bool)
    if expected == "number":
        return isinstance(value, (int, float)) and not isinstance(value, bool)
    raise ValidationError(f"unsupported schema type: {expected}")


def validate(value: Any, schema_node: dict[str, Any], root_schema: dict[str, Any], path: str) -> None:
    if "$ref" in schema_node:
        validate(value, resolve_ref(root_schema, schema_node["$ref"]), root_schema, path)
        return

    if "anyOf" in schema_node:
        errors = []
        for option in schema_node["anyOf"]:
            try:
                validate(value, option, root_schema, path)
                return
            except ValidationError as exc:
                errors.append(str(exc))
        raise ValidationError(f"{path}: value does not match any allowed schema: {errors}")

    if "enum" in schema_node and value not in schema_node["enum"]:
        raise ValidationError(f"{path}: expected one of {schema_node['enum']!r}, got {value!r}")

    expected_type = schema_node.get("type")
    if expected_type is not None:
        expected_types = expected_type if isinstance(expected_type, list) else [expected_type]
        if not any(type_matches(value, item) for item in expected_types):
            raise ValidationError(f"{path}: expected {expected_types!r}, got {type(value).__name__}")

    if value is None:
        return

    if isinstance(value, dict):
        properties = schema_node.get("properties", {})
        if schema_node.get("additionalProperties") is False:
            unknown = sorted(set(value) - set(properties))
            if unknown:
                raise ValidationError(f"{path}: unknown key(s): {', '.join(unknown)}")
        for key, child in value.items():
            if key in properties:
                validate(child, properties[key], root_schema, f"{path}.{key}")
        return

    if isinstance(value, list) and "items" in schema_node:
        for index, item in enumerate(value):
            validate(item, schema_node["items"], root_schema, f"{path}[{index}]")


def main() -> int:
    try:
        config = tomllib.loads(CONFIG.read_text())
        schema = load_schema()
        validate(config, schema, schema, "release-plz.toml")
    except FileNotFoundError as exc:
        print(f"release-plz config validation failed: {exc}", file=sys.stderr)
        return 1
    except subprocess.CalledProcessError as exc:
        print("release-plz config validation failed while generating schema.", file=sys.stderr)
        if exc.stderr:
            print(exc.stderr, file=sys.stderr)
        return exc.returncode
    except (tomllib.TOMLDecodeError, ValidationError) as exc:
        print(f"release-plz config validation failed: {exc}", file=sys.stderr)
        return 1

    print("release-plz.toml validates against the pinned release-plz schema.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
