// Tiny zero-dependency dashboard.
// Reads ./data/state.json, which is regenerated by the `snapshot-dashboard`
// GitHub Action on every issue / project_v2_item event.
//
// Expected schema (kept minimal on purpose):
// {
//   "generatedAt": "ISO-8601",
//   "stats": { "openIssues": n, "inProgress": n, "doneLast30d": n, "currentMilestone": "M0" },
//   "milestones": [{ "name": "M0", "title": "...", "done": n, "total": n }],
//   "activity": [{ "at": "ISO-8601", "kind": "issue.opened", "title": "...", "url": "..." }]
// }

const STATE_URL = "./data/state.json";

function fmtTime(iso) {
    try {
        return new Date(iso).toLocaleString();
    } catch {
        return iso ?? "—";
    }
}

function renderStats(stats) {
    if (!stats) return;
    const map = {
        "open-issues": stats.openIssues,
        "in-progress": stats.inProgress,
        "done-30d": stats.doneLast30d,
        "milestone": stats.currentMilestone,
    };
    for (const [key, value] of Object.entries(map)) {
        const el = document.querySelector(`[data-stat="${key}"]`);
        if (el && value !== undefined && value !== null) {
            el.textContent = String(value);
        }
    }
}

function renderMilestones(list) {
    const container = document.getElementById("milestone-list");
    container.innerHTML = "";
    if (!Array.isArray(list) || list.length === 0) {
        container.innerHTML = '<p class="muted">No milestones yet.</p>';
        return;
    }
    for (const m of list) {
        const pct = m.total > 0 ? Math.round((m.done / m.total) * 100) : 0;
        const node = document.createElement("div");
        node.className = "milestone";
        node.innerHTML = `
            <div class="milestone-head">
                <div><span class="milestone-name">${m.name}</span> — ${m.title ?? ""}</div>
                <div class="muted">${m.done} / ${m.total}</div>
            </div>
            <div class="progress"><div style="width: ${pct}%"></div></div>
        `;
        container.appendChild(node);
    }
}

function renderActivity(list) {
    const container = document.getElementById("activity-list");
    container.innerHTML = "";
    if (!Array.isArray(list) || list.length === 0) {
        container.innerHTML = '<li class="muted">No activity yet.</li>';
        return;
    }
    for (const a of list.slice(0, 20)) {
        const li = document.createElement("li");
        const label = a.kind?.replaceAll(".", " ") ?? "event";
        li.innerHTML = `
            <a href="${a.url ?? "#"}">${a.title ?? "(untitled)"}</a>
            <span class="meta">${label} · ${fmtTime(a.at)}</span>
        `;
        container.appendChild(li);
    }
}

async function boot() {
    try {
        const res = await fetch(STATE_URL, { cache: "no-cache" });
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const state = await res.json();
        renderStats(state.stats);
        renderMilestones(state.milestones);
        renderActivity(state.activity);
        document.getElementById("last-refresh").textContent = fmtTime(state.generatedAt);
    } catch (err) {
        console.error("Dashboard state load failed:", err);
        const stats = document.getElementById("stats");
        const banner = document.createElement("p");
        banner.className = "muted";
        banner.textContent = "Dashboard data not available yet. It will appear after the first CI snapshot.";
        stats.after(banner);
    }
}

boot();
